server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          discovery:
           locator:
            enabled: true
            lower-case-service-id: true
          routes:
            - id: resource-service-route
              uri: lb://resource-service
              predicates:
               - Path=/resources/**
            - id: song-service-route
              uri: lb://song-service
              predicates:
               - Path=/songs/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    show-details: always
