spring:
  application:
    name: storage-service
  datasource:
    url: ${RESOURCE_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/storagedb}
    username: ${RESOURCE_SERVICE_DB_USER:postgres}
    password: ${RESOURCE_SERVICE_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: ${STORAGE_SERVICE_INSIDE_PORT:8084}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    show-details: always

storage:
  paths:
    STAGING: staging/

    PERMANENT: permanent/

